name: Lets Start KaizuryuBot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 5132611794]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'KaizuryuBot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: RimuruDemonlord
          commit_user_email: 102808014+RimuruDemonlord@users.noreply.github.com
          commit_author: RimuruDemonlord <102808014+RimuruDemonlord@users.noreply.github.com>
